/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.controller.CursoIController;
import br.com.ifba.curso.entity.Curso;
import jakarta.annotation.PostConstruct;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Component;

/**
 *
 * @author valdo
 */
@Component//Bean do tipo Component.
public class TelaGerenciamentoCurso extends javax.swing.JFrame {

    private TelaCadastrarCurso tCC;
    private TelaEditarCurso tEC;

    @Autowired//Conecta ao Controller e demais camadas.
    private CursoIController cursoController;

    @Autowired
    private ApplicationContext aC;

    public TelaGerenciamentoCurso() {
        initComponents();
        setLocationRelativeTo(null);
    }

    @PostConstruct
    public void carregarTela() {
        //Inicia os beans das subtelas.
        tCC = aC.getBean(TelaCadastrarCurso.class);
        tEC = aC.getBean(TelaEditarCurso.class);

        this.atualizarTabela();
        this.desabilitarBotoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGerenciamentoCurso = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnCreate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtRead = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciamento de Cursos");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(720, 480));
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tblGerenciamentoCurso.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        tblGerenciamentoCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblGerenciamentoCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblGerenciamentoCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGerenciamentoCursoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblGerenciamentoCurso);

        jPanel3.setBackground(new java.awt.Color(0, 152, 59));
        jPanel3.setPreferredSize(new java.awt.Dimension(240, 360));

        btnCreate.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        btnCreate.setText("Cadastrar");
        btnCreate.setAlignmentX(0.5F);
        btnCreate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        btnUpdate.setText("Editar");
        btnUpdate.setAlignmentX(0.5F);
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        btnDelete.setText("Excluir");
        btnDelete.setAlignmentX(0.5F);
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(227, 25, 25));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO DE CURSOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(btnCreate)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtRead.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        txtRead.setText("Pesquisar...");
        txtRead.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtRead.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtReadMouseClicked(evt);
            }
        });
        txtRead.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtReadKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .addComponent(txtRead))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(txtRead, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//Desabilita botões de Editar e Excluir, limpa a seleção de curso na tabela e restaura a caixa de pesquisa ao estado sem uso.
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        this.tblGerenciamentoCurso.clearSelection();
        this.desabilitarBotoes();
        this.txtRead.setText("Pesquisar...");
    }//GEN-LAST:event_formMouseClicked
//Realiza a pesquisa na tabela de acordo com o texto digitado (Letras com acentos são ignoradas).
    private void txtReadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReadKeyReleased

        this.tblGerenciamentoCurso.clearSelection();
        this.desabilitarBotoes();

        TabelaGerenciamentoCurso tGC = (TabelaGerenciamentoCurso) tblGerenciamentoCurso.getModel();
        TableRowSorter<TabelaGerenciamentoCurso> tRS = new TableRowSorter<>(tGC);

        tblGerenciamentoCurso.setRowSorter(tRS);
        tRS.setRowFilter(RowFilter.regexFilter("(?i)" + txtRead.getText()));
    }//GEN-LAST:event_txtReadKeyReleased
//Limpa a seleção de curso da tabela, desabilita os botões de Editar e Excluir e apaga o texto "Pesquisar..." ao clicar na barra de pesquisa.
    private void txtReadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReadMouseClicked

        this.tblGerenciamentoCurso.clearSelection();
        this.desabilitarBotoes();
        this.txtRead.setText("");
    }//GEN-LAST:event_txtReadMouseClicked
//Seleciona um curso na tabela.
    private void tblGerenciamentoCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGerenciamentoCursoMouseClicked

        this.txtRead.setText("Pesquisar...");

        if (this.CursoSelecionadoTabela() == null) {
            this.desabilitarBotoes();
        }

        this.habilitarBotoes();
        Curso curso = this.CursoSelecionadoTabela();
    }//GEN-LAST:event_tblGerenciamentoCursoMouseClicked
//Exclui determinado curso que está selecionado na tabela.
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        Curso cursoEscolhido = this.CursoSelecionadoTabela();

        this.txtRead.setText("Pesquisar...");
        this.tblGerenciamentoCurso.clearSelection();
        this.desabilitarBotoes();

        int jOP = JOptionPane.showConfirmDialog(null, "Tem certeza de que deseja excluir esse curso?", "Atenção!", JOptionPane.YES_NO_OPTION);

        if (jOP == JOptionPane.YES_OPTION) {
            try {
                cursoController.delete(cursoEscolhido);
                JOptionPane.showMessageDialog(null, "Curso excluído com sucesso!");
            } catch (Exception error) {
                JOptionPane.showMessageDialog(null, error, "Erro", JOptionPane.ERROR_MESSAGE);
            }

            this.atualizarTabela();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed
//Seleciona o curso a ser editado e torna a tela de editar curso visível.
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        Curso cursoEscolhido = CursoSelecionadoTabela();

        this.txtRead.setText("Pesquisar...");
        this.tblGerenciamentoCurso.clearSelection();
        this.desabilitarBotoes();

        tEC.carregarTela(this, cursoEscolhido);
        tEC.setVisible(true);
    }//GEN-LAST:event_btnUpdateActionPerformed
//Torna a tela de adicionar curso visível.
    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        this.txtRead.setText("Pesquisar...");
        this.tblGerenciamentoCurso.clearSelection();
        this.desabilitarBotoes();

        tCC.carregarTela(this);
        tCC.setVisible(true);
    }//GEN-LAST:event_btnCreateActionPerformed
    //Atualiza a tabela assim que um curso é adicionado, editado ou excluído.
    public void atualizarTabela() {
        TabelaGerenciamentoCurso tGC = new TabelaGerenciamentoCurso(cursoController.findAll());
        tblGerenciamentoCurso.setModel(tGC);
    }

    //Obtém as informações de um curso cadastrado que está em determinada linha na tabela.
    public Curso CursoSelecionadoTabela() {
        int linhaSelecionada = tblGerenciamentoCurso.getSelectedRow();

        if (linhaSelecionada >= 0) {
            TabelaGerenciamentoCurso tGC = (TabelaGerenciamentoCurso) tblGerenciamentoCurso.getModel();

            Curso curso = tGC.getObjetoCurso(linhaSelecionada);
            return curso;
        } else {
            return null;
        }
    }

    //Habilita os botões Editar e Excluir.
    private void habilitarBotoes() {
        this.btnUpdate.setEnabled(true);
        this.btnDelete.setEnabled(true);
    }

    //Desabilita os botões Editar e Excluir.
    private void desabilitarBotoes() {
        this.btnUpdate.setEnabled(false);
        this.btnDelete.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciamentoCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciamentoCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciamentoCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciamentoCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerenciamentoCurso().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblGerenciamentoCurso;
    private javax.swing.JTextField txtRead;
    // End of variables declaration//GEN-END:variables
}
